name: PlatformIO
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - lilygo_t_display_s3
          - lilygo_t_dongle_s3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-platformio-${{ matrix.example }}
      - uses: actions/setup-python@v5
      - run: python -m pip install platformio
      - run: pio run --project-dir ${{ matrix.example }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.example }}
          path: ~/.platformio/build/ESP32-Arduino/${{ matrix.example }}/firmware.elf
